### PR TITLE
Get and display all workflows, all jobs per workflow, and last 100 workflow runs in the extension view

### PR DESCRIPTION
**Pull request by KetchupOnMyKetchup**
Closes https://github.com/github/vscode-github-actions/issues/72

- https://github.com/cschleiden/vscode-github-actions/issues/151

New requirement:
1. Get all workflows and paginate using octokit
1. Get all jobs per run and paginate using oktokit
1. Get the last 100 workflow runs

--

**Proof of each of the above 3 requirements:**

1. Get all workflows and paginate using octokit **is already happening so no code changes were needed.** For proof: see screenshot of use of `.paginate` pulling all 33 workflows from a repo and paginating (also tested changing `per_page: 10` to ensure it would still get all 33 workflows and it did):
  image

2. Get all jobs per run and paginate using oktokit. I set per page to 2 in the screenshot below to test and show that it gets all the pages with the `.paginate` code and pulls more than 2 jobs on the right of the screen under a run under both Current Branch and Workflows.
  image

3. Get the last 100 workflow runs demo, by bumping `per_page` to 100 for workflows for the current branch.:
  perpage100

--

Demo showing that workflows, runs, and jobs tree working:
demoworkflows

### CODE REVIEW

**Comment by elbrenn** [comment]
Based on the screenshot in https://github.com/github/vscode-github-actions/issues/72, the issue was about the number of jobs shown for a given workflow run. This is a different api.

**Review by jtamsut — APPROVED** [review]
This looks pretty reasonable to me. Thanks for the screenshots in the PR description. Made understanding the problem very clear. 😄

**Review by elbrenn — COMMENTED** [review]
This PR adds changes to increase page size for workflow runs and fetch all jobs for a workflow run/ workflow run attempt as stated in the PR description 👍 

However I don't see any changes to fetch all workflows. Workflows are fetched in [WorkflowRepoNode](https://github.com/github/vscode-github-actions/blob/ea64b27fa051c0a0792ca02f20502942fc9d2b45/src/treeViews/workflows/workflowsRepoNode.ts#L24)

**Comment by KetchupOnMyKetchup** [comment]
> This PR adds changes to increase page size for workflow runs and fetch all jobs for a workflow run/ workflow run attempt as stated in the PR description 👍
> 
> However I don't see any changes to fetch all workflows. Workflows are fetched in [WorkflowRepoNode](https://github.com/github/vscode-github-actions/blob/ea64b27fa051c0a0792ca02f20502942fc9d2b45/src/treeViews/workflows/workflowsRepoNode.ts#L24)

All workflows are getting fetched already and I put a screenshot in the description to show the code that does it and that I tested it:
image

**Review by elbrenn — APPROVED** [review]

**Pull request merged**
